version: "3"
services:
  master:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --master
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tasks:/locust-tasks
  worker:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --worker --master-host master
    volumes:
      - ./locust-tasks:/locust-tasks
