version: "3"
services:
  master:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --master
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tasks:/locust-tasks
  slave1:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --slave --master-host master
    volumes:
      - ./locust-tasks:/locust-tasks
  slave2:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --slave --master-host master
    volumes:
      - ./locust-tasks:/locust-tasks
  slave3:
    image: locustio/locust
    command: -f /locust-tasks/locustfile.py --slave --master-host master
    volumes:
      - ./locust-tasks:/locust-tasks
  # Add more slave containers as needed
